In [6]:
import numpy as np

from learning_algorithms.network import Network

In [5]:
neural_net = Network(
    [3,3,1],
    output_function=lambda x: x, 
    output_derivative=lambda x: 1
)

In [14]:
y_train = np.random.normal(1, 0.1, 200)
X_train = np.round(np.random.normal(200, 0.5, [200, 3]))

In [19]:
list(zip(X_train, y_train))

# neural_net.SGD(
#     X_train, y_train, 3, int(X_train.shape[0]/3), eta = 0.05)

[(array([200., 200., 199.]), 1.0481909187315661),
 (array([199., 201., 200.]), 0.9676776225636183),
 (array([199., 200., 201.]), 1.1044330061427383),
 (array([201., 200., 200.]), 0.9448958420234546),
 (array([200., 200., 201.]), 0.9078086437470727),
 (array([200., 200., 200.]), 1.0420135165775344),
 (array([200., 200., 200.]), 0.9993256595453005),
 (array([199., 200., 200.]), 0.9711131989466601),
 (array([200., 201., 199.]), 0.8983152258045495),
 (array([200., 199., 200.]), 1.0596108143628693),
 (array([199., 200., 200.]), 1.0945728549926903),
 (array([200., 200., 200.]), 0.960094071691295),
 (array([199., 200., 199.]), 0.8465811616653868),
 (array([200., 199., 200.]), 1.000281955179706),
 (array([200., 200., 200.]), 0.8718167962384652),
 (array([200., 200., 200.]), 1.0436219947303247),
 (array([199., 201., 200.]), 0.8814105617569843),
 (array([200., 199., 199.]), 0.9177080154223521),
 (array([200., 201., 200.]), 1.068114936484063),
 (array([201., 200., 199.]), 1.2154497868324685),
 (a